// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where one game's analysis is in its lifecycle — pushed on the
 * `analysis-status` event so a per-game view (a history card) can show
 * queued / running / done for its own `game_id`. `Running` carries its
 * own progress, so a percent only exists when there's actually one to
 * report. Serialised internally-tagged: `{ "kind": "Running", "percent": 42 }`.
 */
export type AnalysisStage = { "kind": "Queued" } | { "kind": "Running", percent: number, } | { "kind": "Done" } | { "kind": "Failed" };
