// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchLimit } from "./SearchLimit";

/**
 * The analyzer engine's tunable config, as the frontend edits it and the
 * analysis pipeline consumes it. Round-trips through an [`EngineSettings`]
 * row with `engine_role = "analyzer"`.
 */
export type AnalyzerEngineSettings = { search_limit: SearchLimit, multi_pv: number, threads: number, hash_mb: number, };
