// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalysisStage } from "./AnalysisStage";

export type AnalysisStatus = { game_id: number, stage: AnalysisStage, };
