// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * App-level preferences as the frontend edits them — the persisted
 * [`AppSettingsRow`] without the DB-managed id/timestamp. Every field is
 * optional: a user with no chess.com account or no key is a normal
 * state, not a partial write, so the conversion in is a plain `From`.
 */
export type AppSettings = { koch_username: string | null, chessdotcom_username: string | null, openai_key: string | null, };
