// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PvLine } from "./PvLine";

export type EngineSnapshot = { 
/**
 * Sent with the position and echoed back, so the frontend can drop a
 * snapshot that arrives after it has moved on to another position.
 */
position_key: string, depth: number | null, multi_pv: number | null, pv_lines: Array<PvLine>, };
