// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An engine score, always from White's point of view: positive favours
 * White whoever is to move. UCI scores are from the side to move's point
 * of view, so [`EvalScore::from_uci`] flips them here, once, and nothing
 * on the frontend needs to know whose turn it was (KOCH-HANDOFF.md §3).
 */
export type EvalScore = { "kind": "cp", centipawns: number, } | { "kind": "mate", movesToMate: number, };
