// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Fork = { forker_id: number, 
/**
 * Only the targets the fork actually threatens: the king if it's in
 * check, plus every piece the forker's side would win material by
 * capturing. A protected piece that would cost more than it gains
 * isn't forked, however many pieces attack it.
 */
forked_ids: Array<number>, };
