// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who won, or that nobody has yet — the same four outcomes a PGN encodes
 * in its `[Result]` tag and trailing movetext token (`"1-0"`, `"0-1"`,
 * `"1/2-1/2"`, `"*"`). One type for both live play and PGN parsing/export,
 * rather than two enums independently hand-kept in sync.
 *
 * Never accepted as a Tauri command *input* — only ever computed
 * server-side from a `TerminationReason`, or read off a PGN. A client
 * claiming "WhiteWin" directly, with no reason, isn't a thing the app's
 * IPC allows.
 */
export type GameResult = "BlackWin" | "WhiteWin" | "Draw" | "Unfinished";
