// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who won, or that nobody has yet — never accepted as a command *input*,
 * only ever computed server-side from a `TerminationReason` and handed
 * back. A client claiming "WhiteWin" directly, with no reason, isn't a
 * thing this API allows.
 */
export type GameResult = "BlackWin" | "WhiteWin" | "Draw" | "Unfinished";
