// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One saved game, for a game-history / library view — a straight copy of
 * the `games` row (`db::schemas::game::Game`), widened/typed for the
 * frontend the same way every other command payload here is. `opening_id`
 * stays around alongside the resolved `opening_name` (built via
 * `game_summary_from`, not a plain `From` — resolving the name needs a DB
 * connection `Game` alone doesn't carry). `pgn_data` is left off entirely
 * — it's still just an empty-string placeholder until a real PGN
 * serializer exists.
 */
export type GameSummary = { game_id: number, game_hash: string, date_played: string | null, white_player: string, black_player: string, white_elo: number, black_elo: number, result: string, opening_id: number | null, opening_name: string | null, time_control: string | null, source: string, human_color: string | null, 
/**
 * Whether this game has an aggregate `analysis` row — drives the
 * analysed/not-analysed marker in the history card, nothing more. The
 * actual analysis numbers are fetched separately when a game is opened.
 */
has_analysis: boolean, 
/**
 * An import whose movetext stopped part way — the move list is a
 * prefix. The history card flags it so a partial game isn't mistaken
 * for a complete one.
 */
partial_import: boolean, };
