// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameSummary } from "./GameSummary";
import type { ReplayPosition } from "./ReplayPosition";
import type { SideAccuracy } from "./SideAccuracy";

export type GameReplay = { summary: GameSummary, 
/**
 * `positions[0]` is the start position and `positions[n]` the position
 * after `n` plies — so there is always one more position than moves.
 */
positions: Array<ReplayPosition>, 
/**
 * Each player's accuracy. `None` when the game hasn't been analysed,
 * or its analysis predates per-side numbers.
 */
white_accuracy: SideAccuracy | null, black_accuracy: SideAccuracy | null, };
