// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MoveQualityEntry } from "./MoveQualityEntry";

export type GameAnalysis = { 
/**
 * Win%-based accuracy, averaged per move — the same curve Lichess's
 * accuracy model uses. A move that costs no win% scores ~100, a
 * game-losing blunder approaches 0.
 */
accuracy_percent: number, average_centipawn_loss: number, 
/**
 * Only the human's moves — grading the engine's own moves isn't useful.
 */
move_qualities: Array<MoveQualityEntry>, 
/**
 * Eval after every ply (index 0 is the start position), always from
 * White's perspective so the frontend can plot it directly without
 * re-deriving a sign per point.
 */
centipawn_history: Array<number>, 
/**
 * Everything below is derived from `move_times_ms` alone — no engine
 * involved, unlike the fields above.
 */
average_move_time_ms: number, longest_think_ms: number, longest_think_ply: number | null, 
/**
 * How many of the human's moves were made with less than
 * `TIME_TROUBLE_THRESHOLD_MS` left on their own clock.
 */
time_trouble_moves: number, 
/**
 * The human's own per-move times, in ply order.
 */
human_move_times_ms: Array<number>, 
/**
 * Sum of every move's time, both sides — actual wall-clock game
 * length, not just the human's share of it.
 */
total_duration_ms: number, };
