// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MoveQualityEntry } from "./MoveQualityEntry";
import type { PositionFindings } from "./PositionFindings";
import type { SideAccuracy } from "./SideAccuracy";

export type GameAnalysis = { 
/**
 * Win%-based accuracy, averaged per move — the same curve Lichess's
 * accuracy model uses. A move that costs no win% scores ~100, a
 * game-losing blunder approaches 0.
 *
 * These two are the human's side only — the same numbers as `white`
 * or `black` for that colour — because they feed what's about *you*:
 * the post-game card and your average accuracy across games.
 */
accuracy_percent: number, average_centipawn_loss: number, 
/**
 * Each side's own accuracy, for comparing the two players.
 */
white: SideAccuracy, black: SideAccuracy, 
/**
 * Every move, both sides; `mover` on each entry says whose.
 */
move_qualities: Array<MoveQualityEntry>, 
/**
 * Eval after every ply (index 0 is the start position), always from
 * White's perspective so the frontend can plot it directly without
 * re-deriving a sign per point.
 */
centipawn_history: Array<number>, 
/**
 * Everything below is derived from `move_times_ms` alone — no engine
 * involved, unlike the fields above.
 */
average_move_time_ms: number, longest_think_ms: number, longest_think_ply: number | null, 
/**
 * How many of the human's moves were made while low on their own clock.
 */
time_trouble_moves: number, 
/**
 * The human's own per-move times, in ply order.
 */
human_move_times_ms: Array<number>, 
/**
 * Sum of every move's time, both sides — actual wall-clock game
 * length, not just the human's share of it.
 */
total_duration_ms: number, 
/**
 * Deterministic analyzer findings after every ply, same indexing as
 * `centipawn_history` (index 0 is the start position) — every position
 * gets analyzed, not just the human's moves, so any point in the game
 * can be explained later, not only the ones that were scored.
 */
position_findings: Array<PositionFindings>, };
