// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameResult } from "./GameResult";
import type { LastMove } from "./LastMove";
import type { PieceColor } from "./PieceColor";
import type { PieceView } from "./PieceView";
import type { Square } from "./Square";

/**
 * Board snapshot the frontend renders from. Shared between `start_game`
 * and (eventually) `make_move` — everything here changes on every move
 * except `move_history` only growing.
 */
export type GameStateView = { turn: PieceColor, pieces: Array<PieceView>, 
/**
 * Piece id -> its legal destination squares (quiet moves and captures
 * merged — the frontend doesn't need the distinction to highlight
 * legal squares). Dropped `PieceMoves::attacks` entirely: that's for
 * check detection internally, not something the frontend needs yet.
 */
legal_moves: { [key in number]?: Array<Square> }, 
/**
 * SAN, e.g. `["e4", "e5", "Nf3"]` — empty right after `start_game`.
 */
move_history: Array<string>, 
/**
 * None right after `start_game`, before anyone has moved.
 */
last_move: LastMove | null, 
/**
 * The most specific catalogued opening reached so far, or None before
 * any moves / once the game has gone off any known book line.
 */
opening_name: string | null, result: GameResult, white_remaining_ms: number, black_remaining_ms: number, 
/**
 * Milliseconds elapsed in the current side-to-move's turn, as of when
 * this snapshot was built. Not a live-ticking value — the frontend
 * combines this with its own locally-elapsed time since receiving the
 * response to keep a countdown display without needing synchronized
 * clocks, the same "backend stores a deadline, frontend ticks the
 * display" split discussed for clocks generally.
 */
elapsed_this_turn_ms: number, };
