// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `import_pgn` tells the popup once it's done.
 */
export type ImportPgnResult = { 
/**
 * The new `games` row id, or `null` if this exact game was already in
 * the library (dedup by move sequence).
 */
game_id: number | null, imported_plies: number, 
/**
 * Set when the movetext stopped replaying early — the 1-based ply that
 * failed and the SAN token that couldn't be read.
 */
truncated_at_ply: number | null, truncated_token: string | null, };
