// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much trouble a king is in, as a band rather than a number. The raw
 * score is an open-ended sum of three penalties, so "22" on its own says
 * nothing to anyone who doesn't know the formula — "uneasy" does.
 */
export type KingDanger = "Safe" | "Uneasy" | "Exposed" | "Critical";
