// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PieceColor } from "./PieceColor";

/**
 * Deterministic king-safety heuristic for one color's king. `score` is a
 * danger magnitude - always >= 0, higher means less safe - not a signed
 * eval contribution, so it needs no color-relative sign flip when reading
 * it back.
 */
export type KingSafety = { color: PieceColor, score: number, shield_penalty: number, 
/**
 * Capped at `STORM_PENALTY_CAP`, so once several pawns are bearing down
 * this total is less than the sum of what each pawn in
 * `storming_pawn_ids` contributed on its own.
 */
storm_penalty: number, attack_penalty: number, missing_shield_files: Array<number>, advanced_shield_pawn_ids: Array<number>, storming_pawn_ids: Array<number>, attacking_piece_ids: Array<number>, };
