// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Square } from "./Square";

/**
 * The two squares of the most recently played move — for highlighting it
 * on the board, distinct from `selectedSquare` (which is about the
 * player's *next* move, not the one that just happened).
 */
export type LastMove = { from: Square, to: Square, };
