// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The live engine's Stockfish options. Kept in memory for as long as the
 * app runs and never saved — deliberately separate from the saved
 * analyzer settings the post-game pass is configured with.
 */
export type LiveEngineSettings = { multi_pv: number, threads: number, hash_mb: number, };
