// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MoveQuality } from "./MoveQuality";

export type MoveQualityEntry = { ply_number: number, quality: MoveQuality, centipawn_loss: number, };
