// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MoveQuality } from "./MoveQuality";
import type { PieceColor } from "./PieceColor";

export type MoveQualityEntry = { ply_number: number, 
/**
 * Whose move this was. Every move is graded now, so anything about
 * one player — "your blunders", "your worst move" — has to filter on
 * this rather than assume the list is theirs.
 */
mover: PieceColor, quality: MoveQuality, centipawn_loss: number, };
