// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PieceColor } from "./PieceColor";

export type PawnStructure = { color: PieceColor, pawn_islands: Array<Array<number>>, backward_pawn_ids: Array<number>, passed_pawn_ids: Array<number>, isolated_pawn_ids: Array<number>, doubled_pawn_ids: Array<number>, 
/**
 * True per file where this color has no pawn. Only reflects this
 * color's own pawns - a `true` here can mean the file is fully open or
 * that the opponent still holds it, and telling those apart needs
 * [`Board::file_states`], which looks at both colors.
 */
unoccupied_files: [boolean, boolean, boolean, boolean, boolean, boolean, boolean, boolean], };
