// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PieceColor } from "./PieceColor";
import type { PieceType } from "./PieceType";
import type { Square } from "./Square";

/**
 * One piece on the board, flattened for the frontend — just enough to
 * render it, not `koch_engine::ChessPiece`'s internal `has_moved` etc.
 */
export type PieceView = { id: number, kind: PieceType, color: PieceColor, square: Square, };
