// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Square } from "./Square";

export type Pin = { pin_target_id: number, pinned_piece_id: number, pinner_piece_id: number, squares: Array<Square>, };
