// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The opponent engine's tunable config — performance only, no strength
 * knobs. Round-trips through an [`EngineSettings`] row with
 * `engine_role = "player"`; the analyzer-only columns stay NULL.
 */
export type PlayerEngineSettings = { threads: number, hash_mb: number, move_overhead_ms: number, ponder: boolean, };
