// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The headline numbers shown on the Home screen. Derived on demand from
 * `games` / `analysis` / `time_logs`; only the rating has its own table.
 */
export type PlayerStats = { current_rating: number, 
/**
 * Mean accuracy over analysed human games, 0–100. `0` when none.
 */
avg_accuracy: number, 
/**
 * Share of decisive-or-drawn human games that were wins, 0–100.
 */
win_rate: number, games_played: number, 
/**
 * Longest run of consecutive human wins, in date order.
 */
best_streak: number, 
/**
 * Total time connected, summed over completed sessions.
 */
total_seconds: number, };
