// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Fork } from "./Fork";
import type { KingSafety } from "./KingSafety";
import type { PawnStructure } from "./PawnStructure";
import type { Pin } from "./Pin";
import type { Square } from "./Square";

/**
 * A single position's worth of every deterministic analyzer signal, bundled
 * for a caller (namely `GameAnalysis` - see KOCH-9) that wants one object
 * per ply rather than several separate parallel collections. Per-square
 * data (`square_threats`/`attackers`/`defenders`) is `Vec`, not a fixed
 * `[T; 64]` array - still indexed by `Square::index()` - since ts-rs
 * renders a 64-element array as a 64-tuple TS type, which is technically
 * valid but unusable from the frontend.
 */
export type PositionFindings = { 
/**
 * Net attackers per square, indexed by `Square::index()`. **Negative
 * means White threatens the square more, positive means Black does** -
 * deliberately the reverse of the "+ favours White" convention used by
 * engine evals like `centipawn_history`, because this counts *pressure*
 * rather than advantage. A 0 can mean either untouched or evenly
 * contested; `attackers`/`defenders` tell those apart.
 */
square_threats: Array<number>, hanging_squares: Array<Square>, 
/**
 * Ids of the White pieces covering each square, indexed by
 * `Square::index()` - "attackers" and "defenders" here are White and
 * Black, not relative to whoever owns the piece standing there.
 */
attackers: Array<Array<number>>, defenders: Array<Array<number>>, pins: Array<Pin>, forks: Array<Fork>, white_pawn_structure: PawnStructure, black_pawn_structure: PawnStructure, white_king_safety: KingSafety, black_king_safety: KingSafety, };
