// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvalScore } from "./EvalScore";

export type PvLine = { score: EvalScore, moves: Array<string>, };
