// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LastMove } from "./LastMove";
import type { MoveQuality } from "./MoveQuality";
import type { PieceView } from "./PieceView";
import type { PositionFindings } from "./PositionFindings";

/**
 * One position a saved game passed through — the start position, or the
 * position just after one of its moves. The move-related fields are about
 * the move that *produced* this position, so they're all `None` for the
 * start position.
 */
export type ReplayPosition = { pieces: Array<PieceView>, findings: PositionFindings, last_move: LastMove | null, san: string | null, uci: string | null, 
/**
 * How long the move took to play.
 */
time_ms: number | null, 
/**
 * White-relative engine eval of this position, in centipawns. `None`
 * until the game has been analysed.
 */
eval_cp: number | null, 
/**
 * How good the move was. `None` until the game has been analysed —
 * and for an analysis saved before both sides were graded, `None` on
 * the opponent's moves until it's re-analysed.
 */
quality: MoveQuality | null, };
