// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which quantity bounds one analyzer search. The DB stores this as the
 * `search_limit` TEXT column (see [`SearchLimitMode::as_db_str`]); the
 * paired amount goes in `search_limit_value`.
 */
export type SearchLimitMode = "Depth" | "MoveTime" | "Nodes";
