// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchLimitMode } from "./SearchLimitMode";

/**
 * A stop condition for one analyzer pass: `mode` and how much of it
 * (plies for `Depth`, milliseconds for `MoveTime`, a node count for
 * `Nodes`). `u32` — a node cap in the low billions is already far past
 * anything useful here, and it keeps the TS binding a plain `number`.
 */
export type SearchLimit = { mode: SearchLimitMode, value: number, };
