// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One side's accuracy over a game.
 */
export type SideAccuracy = { 
/**
 * Win%-based accuracy, averaged per move — see `GameAnalysis`.
 */
accuracy_percent: number, average_centipawn_loss: number, };
