// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * *Why* a game ended — distinct from `GameResult`, which only says *who*
 * won. Resignation and Timeout don't determine a winner by themselves
 * (either side could be the one who resigned/flagged), so `end_game` also
 * takes `losing_side` for those two; the others are unambiguous on their
 * own (checkmate's loser is whoever was to move, the rest are draws).
 */
export type TerminationReason = "Resignation" | "Timeout" | "Checkmate" | "Stalemate" | "DrawAgreement" | "FiftyMoveRule";
