// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Starting clock time plus the Fischer increment added back after each
 * move, both in milliseconds. Raw numbers, not a named preset like
 * "Blitz" — the frontend's mode picker translates its own presets into
 * this before it ever crosses the boundary, so the backend doesn't need
 * to know preset names exist.
 */
export type TimeControl = { initial_ms: number, increment_ms: number, };
